### PR TITLE
Fix 2 typos and 1 comma-o.

### PR DESCRIPTION
**Pull request by kareman**
I only changed 2 words and removed a comma, no idea why Git/GitHub thinks I wrote the whole thing.

### CODE REVIEW

**Comment by SteveFortune** [comment]
Hi @kareman, thanks for the contribution. Which typos and comma did you amend ? Could you address this PR to the `dev` branch ?

Steve.

**Comment by kareman** [comment]
@SteveFortune 

Sorry didn't see the Contributions.md in the Docs folder.

Do you know what encoding this file is in? Because when I save it on GitHub.com, in TextEdit or in TextMate Git says large parts of the file has been changed even though I haven't made any changes. I'm using UTF-8 as always. The file is also using carriage return instead of newlines.

**Comment by SteveFortune** [comment]
@kareman No worries. I'm not entirely sure what encoding it is, I'm using [this markdown editor](http://25.io/mou/) which doesn't seem to present any char encoding options. 

Running `file -I Docs/Usage.md` gives me `... text/plain; charset=us-ascii` but it doesn't contain any discernible UTF-8 chars. I have recreated your issue with several of the markdown files by open them in Atom (UTF-8 as the default) and re-saving them. 

I'll open a separate ticket to address the issue. 

Thanks again,
Steve.

**Comment by SteveFortune** [comment]
I have news on this. See #67

**Comment by SteveFortune** [comment]
Encoding issues should be fixed in the Markdown files now.

**Comment by kareman** [comment]
@SteveFortune  That covers the 2 typos, I forgot where the comma was.

**Comment by SteveFortune** [comment]
Cool, all merged. Thanks !

**Pull request closed without merging**
